Added one test of the superprefix+prefix attacks. Will add subsequent ones. Theres an error with v3. It produces the following error
```
AssertionError: This entire policy hardcoded for a victim prefix and attacker subprefix Not going to make this dynamic because this is a useless policy
```